#!/bin/bash
today="$(date +%y%m%d)"

# Download the safecast dataset
wget https://api.safecast.org/system/measurements.tar.gz -O ${today}_measurements.tgz
rm -rf  measurements-out.csv 
tar xvfz ${today}_measurements.tgz

# Compute the summary
python safecastSummary.py -l measurements-out.csv

# Render summary map
python safecastSummaryMap.py
